
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jul 03 14:04:12 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int PLUSPLUS = 14;
  public static final int MAP = 32;
  public static final int LBRACKET = 6;
  public static final int CONST = 5;
  public static final int NOTEQUAL = 16;
  public static final int SEMI = 41;
  public static final int LPAREN = 8;
  public static final int GREATER = 18;
  public static final int CONTINUE = 31;
  public static final int LESS = 19;
  public static final int MINUS = 11;
  public static final int RPAREN = 9;
  public static final int AND = 22;
  public static final int OR = 23;
  public static final int COMMA = 44;
  public static final int CLASS = 37;
  public static final int EQUALEQUAL = 15;
  public static final int DIV = 13;
  public static final int PLUS = 12;
  public static final int LESSEQ = 21;
  public static final int IF = 27;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int MINUSMINUS = 33;
  public static final int EQUAL = 40;
  public static final int RBRACKET = 7;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int NUMBER = 45;
  public static final int MOD = 17;
  public static final int BREAK = 43;
  public static final int IDENT = 39;
  public static final int VOID = 34;
  public static final int EQGRE = 25;
  public static final int COLON = 36;
  public static final int LBRACE = 3;
  public static final int ELSE = 26;
  public static final int POINT = 24;
  public static final int READ = 30;
  public static final int WHILE = 29;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 38;
  public static final int PROG = 2;
  public static final int MULTI = 10;
  public static final int BOOL_CONST = 46;
  public static final int GREEQ = 20;
  public static final int PRINT = 35;
}

